version: 0.1
phases:
  install:
    commands:
      - npm install time
      - npm install mocha
      - npm run test
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket devopsgul
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
